### ISSUE TITLE
Add ticket filter ability with the new query param

### ISSUE THREAD

**Issue by gtapps** [mpclarkson/freshdesk-bundle#1]
Hello guys,

Freshdesk added this new parameter which allow us to query the tickets more specific:
https://developer.freshdesk.com/api/#filter_tickets

Would be nice to add it to the PHP SDK.

Cheers.

**Comment by mpclarkson** [comment]
PRs welcome :)

**Comment by gtapps** [comment]
I noticed you can do this now like this:
$ticket = $api->tickets->all($something, [
 'status' => 2
]);
